match:
	python -m dialog.main --noload --config_id 10 > results/25-match-0.txt
	#python -m dialog.main --noload --config_id 11 > results/new-long-match-1.txt
	#python -m dialog.main --noload --config_id 12 > results/new-long-match-2.txt
dstc:
	python -m dialog.main --noload --config_id 20
	python -m dialog.main --noload --config_id 21
wrong:

	#python -m dialog.main --noload --config_id 0
	python -m dialog.main --noload --config_id 1
	python -m dialog.main --noload --config_id 2
dialog0:
	CUDA_VISIBLE_DEVICES= python -m dialog.main --noload --config_id 0
dialogall:
	python -m dialog.main --noload --config_id 2
	python -m dialog.main --noload --config_id 3
	python -m dialog.main --noload --config_id 4
	python -m dialog.main --noload --config_id 5
dialog2:
	python -m dialog.main --noload --config_id 0
	python -m dialog.main --noload --config_id 1
dialog2v:
	python -m dialog.main --noload --config_id 2
	python -m dialog.main --noload --config_id 3
dialog3:
	python -m dialog.main --noload --config_id 4
	python -m dialog.main --noload --config_id 5
0:
	python -m babi.main --noload --config_id 0
1:
	python -m babi.main --noload --config_id 1
res:
	python -m babi.main --noload --config_id 2
	python -m babi.main --noload --config_id 3
dropout:
	python -m babi.main --noload --config_id 4
	python -m babi.main --noload --config_id 5
paper:
	python -m babi.main --noload --config_id 10
	python -m babi.main --noload --config_id 11
2v3v:
	python -m babi.main --noload --config_id 10
	python -m babi.main --noload --config_id 11
adadelta:
	python -m babi.main --noload --config_id 6
